/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "outline-variant": "#c2c6d1",
        "surface-container-low": "#f3f3f9",
        outline: "#737781",
        "on-surface": "#1a1c20",
        "on-primary-container": "#9ac2ff",
        "on-secondary-fixed-variant": "#354958",
        "on-tertiary-fixed": "#2f1500",
        "secondary-fixed-dim": "#b4c9db",
        "error-container": "#ffdad6",
        "tertiary-container": "#793f00",
        "surface-tint": "#2f5f9b",
        "secondary-fixed": "#d0e5f8",
        "on-primary": "#ffffff",
        primary: "#00386b",
        "on-background": "#1a1c20",
        secondary: "#4d6170",
        "surface-container-highest": "#e2e2e8",
        "inverse-primary": "#a5c8ff",
        tertiary: "#582c00",
        "surface-container": "#ededf3",
        surface: "#f9f9ff",
        "on-surface-variant": "#424750",
        "tertiary-fixed-dim": "#ffb77e",
        "primary-fixed": "#d4e3ff",
        "on-secondary-container": "#536777",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#1a4f8a",
        "on-primary-fixed": "#001c3a",
        "on-secondary-fixed": "#081d2b",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2e3035",
        "primary-fixed-dim": "#a5c8ff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdcc3",
        "surface-dim": "#d9dadf",
        "surface-container-high": "#e8e8ed",
        "secondary-container": "#d0e5f8",
        "on-tertiary-container": "#ffae6b",
        background: "#f9f9ff",
        "surface-variant": "#e2e2e8",
        "surface-bright": "#f9f9ff",
        "on-primary-fixed-variant": "#0d4782",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f0f6",
        // Keeping municipal as alias for primary-container
        municipal: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#badffd',
          300: '#7cc2fb',
          400: '#38a0f7',
          500: '#1a4f8a',
          600: '#0d3d75',
          700: '#0b315e',
          800: '#0d2b4f',
          900: '#0e2543',
          DEFAULT: '#1a4f8a',
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "stack-md": "16px",
        unit: "4px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        gutter: "16px",
        "sidebar-width": "260px",
        "container-padding": "24px"
      },
      fontFamily: {
        sans: ["Public Sans", "sans-serif"],
        display: ["Public Sans", "sans-serif"],
        h1: ["Public Sans", "sans-serif"],
        h2: ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "label-bold": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        h1: ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "table-data": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        h2: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        display: ["32px", { lineHeight: "40px", fontWeight: "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
